name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2        
          
      - name: Pull changes and reload Gunicorn
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          ssh $USERNAME@$SERVER_IP << 'EOF'
            docker exec 96170f26ba68 bash -c "
            cd docker_test && \
            git pull origin main && \
            kill -HUP \$(pgrep gunicorn)
            "
          EOF
