name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2 
        
      - name: Set up SSH for server access
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
     
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2
        
      - name: Run commands inside Docker container
        env:
          CONTAINER_NAME: friendly_kilby
        run: |
          # Pull the latest image (if applicable) and run the container
          docker pull your_image:latest
          
          # Run the commands inside the running container
          docker exec -u root $CONTAINER_NAME bash -c "
            cd docker_test && \
            git pull origin main && \
            pip install -r requirements.txt && \
            # Run Gunicorn to start the application
            gunicorn --workers 3 --bind 0.0.0.0:8010 myproject.wsgi:application
          "
          

